apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventapp-db
  namespace: eventapp-prod
spec:
  serviceName: eventapp-db
  replicas: 1
  selector:
    matchLabels:
      app: eventapp-db
  template:
    metadata:
      labels:
        app: eventapp-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: eventhorizon
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
